#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Feb 26 17:54:57 CET 2025
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 2c174372a5a041848693ccac709b3802 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot dfs_top_tb_behav xil_defaultlib.dfs_top_tb -log elaborate.log"
xelab -wto 2c174372a5a041848693ccac709b3802 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot dfs_top_tb_behav xil_defaultlib.dfs_top_tb -log elaborate.log

